### ISSUE TITLE
DOC-1.2.2 - Backend Functional Requirements

### ISSUE THREAD

**Issue by BigBen03** [Elite-Capstone/Project-ShutTheFrontDoor#36]

**Comment by nickydime** [comment]
@BigBen03 We did this right? If so let me know I will close the issue.

**Comment by BigBen03** [comment]
We essentially did what we knew up to now. So you can close this issue. We can add the rest (if we add it at all) when we have more information

**Comment by nickydime** [comment]
Perfect. Closing issue now.
