### ISSUE TITLE
Make list of tools used during design phase

### ISSUE THREAD

**Issue by BigBen03** [Elite-Capstone/Project-ShutTheFrontDoor#60]
Ben: I used OrCAD Pspice and draw.io for the flow chart

**Comment by nickydime** [comment]
Draw.io for flowchart
Azure for CosmosDB set up
Azure for Blob Storage set up

**Comment by RaduP13** [comment]
draw.io
google forms
survey monkey

**Comment by BigBen03** [comment]
Google sheets and schematic/flow chart standards IEC/ISO

**Comment by superDeano** [comment]
I used:
 Sketch for ui sketches design, 
omnigaffle for the different charts and diagrams,
Android studio to create project. 
GitKraken for committing the stuffs I made.

**Comment by nickydime** [comment]
Tools discussed in the report:
- Draw.io
- Survey Monkey/Google Forms
- Google Sheets
- Sketch
- Android Studio
- Azure
