### ISSUE TITLE
Review and Add Alternatives tables for Software

### ISSUE THREAD

**Issue by BigBen03** [Elite-Capstone/Project-ShutTheFrontDoor#62]
Review existing tables with user centered ideology
Add new alternatives tables for selected components for the project

Topics to discuss:
Dean: Communication protocols
Nick:  Choices for Cloud Host

**Comment by nickydime** [comment]
@superDeano Let me know when you'd like to discuss this to possibly add tables.

**Comment by nickydime** [comment]
Flowcharts deemed adequate by myself and @superDeano. Will add more charts if really needed.
